version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: the-rice-bowl
    container_name: the-rice-bowl-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - the-rice-bowl

  nginx:
    image: nginx:alpine
    container_name: the-rice-bowl-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - the-rice-bowl

networks:
  the-rice-bowl:
    driver: bridge