version: '3.7'
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: thericebowl
        container_name: thericebowl-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - thericebowl
    db:
        image: postgres:latest
        container_name: thericebowl-db
        restart: unless-stopped
        environment:
            POSTGRES_DATABASE: ${DB_DATABASE}
            POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_HOST: ${DB_HOST}
            SERVICE_TAGS: dev
            SERVICE_NAME: postgres
        volumes:
            - ./docker-compose/pgsql:/docker-entrypoint-initdb.d
        networks:
            - thericebowl
    nginx:
        image: nginx:alpine
        container_name: thericebowl-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx/:/etc/nginx/conf.d/
        networks:
            - thericebowl

networks:
    thericebowl:
        driver: bridge
